"use client";

import { useFormContext } from "react-hook-form";

import FormSpacerWrapper from "@/components/form-spacer-wrapper";
import Formheader from "@/components/form-header";
import {
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { LAB_SECTIONS, LAB_STATUSES } from "../constants";
import type { CreateLabIdentityValues } from "./lab-form-types";

export function LabIdentityForm({
  isSubmitting,
  formTitle = "Register laboratory",
}: {
  isSubmitting: boolean;
  formTitle?: string;
}) {
  const form = useFormContext<CreateLabIdentityValues>();

  return (
    <FormSpacerWrapper>
      <Formheader title={formTitle} step={1} />
      <FormField
        control={form.control}
        name="internalId"
        rules={{ required: "Lab ID is required" }}
        render={({ field }) => (
          <FormItem>
            <FormLabel required>Lab ID</FormLabel>
            <FormControl>
              <Input {...field} disabled />
            </FormControl>
            <FormDescription>
              Autogenerated unique identifier for the laboratory.
            </FormDescription>
            <FormMessage />
          </FormItem>
        )}
      />
      <FormField
        control={form.control}
        name="name"
        rules={{ required: "Lab name is required" }}
        render={({ field }) => (
          <FormItem>
            <FormLabel required>Lab Name</FormLabel>
            <FormControl>
              <Input
                autoFocus
                placeholder="e.g. Soil Mechanics Laboratory"
                {...field}
                disabled={isSubmitting}
              />
            </FormControl>
            <FormMessage />
          </FormItem>
        )}
      />

      <FormField
        control={form.control}
        name="description"
        render={({ field }) => (
          <FormItem>
            <FormLabel>Description</FormLabel>
            <FormControl>
              <Textarea
                placeholder="Scope of testing, specialisations, and responsibilities"
                {...field}
                disabled={isSubmitting}
              />
            </FormControl>

            <FormMessage />
          </FormItem>
        )}
      />

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-4">
        <FormField
          control={form.control}
          name="labSection"
          rules={{ required: "Lab section is required" }}
          render={({ field }) => (
            <FormItem>
              <FormLabel required>Lab Section</FormLabel>
              <Select
                onValueChange={field.onChange}
                value={field.value}
                disabled={isSubmitting}
              >
                <FormControl>
                  <SelectTrigger>
                    <SelectValue placeholder="Select section" />
                  </SelectTrigger>
                </FormControl>
                <SelectContent>
                  {LAB_SECTIONS.map((section) => (
                    <SelectItem key={section.value} value={section.value}>
                      {section.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="status"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Status</FormLabel>
              <Select
                onValueChange={field.onChange}
                value={field.value}
                disabled={isSubmitting}
              >
                <FormControl>
                  <SelectTrigger>
                    <SelectValue placeholder="Select status" />
                  </SelectTrigger>
                </FormControl>
                <SelectContent>
                  {LAB_STATUSES.map((status) => (
                    <SelectItem key={status.value} value={status.value}>
                      {status.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="capacity"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Workstation Capacity</FormLabel>
              <FormControl>
                <Input
                  type="number"
                  min={1}
                  placeholder="e.g. 8"
                  {...field}
                  disabled={isSubmitting}
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="location"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Location</FormLabel>
              <FormControl>
                <Input
                  placeholder="Building, floor, or site location"
                  {...field}
                  disabled={isSubmitting}
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
      </div>
    </FormSpacerWrapper>
  );
}
